### ISSUE TITLE
Make buildable with the icon

### ISSUE THREAD

**Issue by Sogolumbo** [Sogolumbo/Slight-backup#1]
I don't know how to build the app with the icon.
There should be an easy, if not automated way to build the app with the icon.

There are instructions at the upstream repository from @lengfeld. But I don't know where I need to enter the command `$ make  # generate the lauchner.png's`.

**Comment by Sogolumbo** [comment]
@lengfeld might know how to do this.

**Comment by lengfeld** [comment]
You have to execute the command `make` in the toplevel directory of the repository. It's the directory that contains the file `Makefile`. See also https://www.gnu.org/software/make/manual/html_node/Introduction.html

**Comment by Sogolumbo** [comment]
Thanks a lot.
